// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	attestation "github.com/brave/nitriding/attestation"
	certificate "github.com/brave/nitriding/certificate"

	mock "github.com/stretchr/testify/mock"
)

// Attester is an autogenerated mock type for the Attester type
type Attester struct {
	mock.Mock
}

// GetAttestCert provides a mock function with given fields:
func (_m *Attester) GetAttestCert() (certificate.PrivilegedCert, error) {
	ret := _m.Called()

	var r0 certificate.PrivilegedCert
	if rf, ok := ret.Get(0).(func() certificate.PrivilegedCert); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificate.PrivilegedCert)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAttestDoc provides a mock function with given fields: nonce, userData
func (_m *Attester) GetAttestDoc(nonce []byte, userData []byte) (attestation.CBOR, error) {
	ret := _m.Called(nonce, userData)

	var r0 attestation.CBOR
	if rf, ok := ret.Get(0).(func([]byte, []byte) attestation.CBOR); ok {
		r0 = rf(nonce, userData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(attestation.CBOR)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte, []byte) error); ok {
		r1 = rf(nonce, userData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAttester interface {
	mock.TestingT
	Cleanup(func())
}

// NewAttester creates a new instance of Attester. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAttester(t mockConstructorTestingTNewAttester) *Attester {
	mock := &Attester{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
