// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PathValidator is an autogenerated mock type for the PathValidator type
type PathValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: path
func (_m *PathValidator) Validate(path string) error {
	ret := _m.Called(path)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPathValidator interface {
	mock.TestingT
	Cleanup(func())
}

// NewPathValidator creates a new instance of PathValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPathValidator(t mockConstructorTestingTNewPathValidator) *PathValidator {
	mock := &PathValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
