// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProxyConfigurator is an autogenerated mock type for the ProxyConfigurator type
type ProxyConfigurator struct {
	mock.Mock
}

// ConfigureSOCKSProxy provides a mock function with given fields:
func (_m *ProxyConfigurator) ConfigureSOCKSProxy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigureVIProxy provides a mock function with given fields:
func (_m *ProxyConfigurator) ConfigureVIProxy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProxyConfigurator interface {
	mock.TestingT
	Cleanup(func())
}

// NewProxyConfigurator creates a new instance of ProxyConfigurator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProxyConfigurator(t mockConstructorTestingTNewProxyConfigurator) *ProxyConfigurator {
	mock := &ProxyConfigurator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
