// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PublicKey is an autogenerated mock type for the PublicKey type
type PublicKey struct {
	mock.Mock
}

type mockConstructorTestingTNewPublicKey interface {
	mock.TestingT
	Cleanup(func())
}

// NewPublicKey creates a new instance of PublicKey. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPublicKey(t mockConstructorTestingTNewPublicKey) *PublicKey {
	mock := &PublicKey{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
