// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	certificate "github.com/blocky/nitriding/internal/certificate"

	mock "github.com/stretchr/testify/mock"

	tls "crypto/tls"
)

// TLSBundle is an autogenerated mock type for the TLSBundle type
type TLSBundle struct {
	mock.Mock
}

// GetCert provides a mock function with given fields: ctx
func (_m *TLSBundle) GetCert(ctx context.Context) (certificate.Cert, error) {
	ret := _m.Called(ctx)

	var r0 certificate.Cert
	if rf, ok := ret.Get(0).(func(context.Context) certificate.Cert); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(certificate.Cert)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetConfig provides a mock function with given fields:
func (_m *TLSBundle) GetConfig() (*tls.Config, error) {
	ret := _m.Called()

	var r0 *tls.Config
	if rf, ok := ret.Get(0).(func() *tls.Config); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tls.Config)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewTLSBundle interface {
	mock.TestingT
	Cleanup(func())
}

// NewTLSBundle creates a new instance of TLSBundle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTLSBundle(t mockConstructorTestingTNewTLSBundle) *TLSBundle {
	mock := &TLSBundle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
